spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usercontrolservice?useSSL=false&verifyServerCertificate=false
    username: root
    password: usercontrolservice
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

  freemarker:
    suffix: .html

user-auth:
  crypt-password:
    salt: $2a$10$fLQ5ESJvMlJVoVo1m7ww0.
